spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/festanow
    username: festanow
    password: Tucunare@10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
